#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PueblosMagicos.Android.Inventario.Resource", IsApplication=true)]

namespace PueblosMagicos.Android.Inventario
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f01001a
			public const int buttonSize = 2130771994;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010012
			public const int cameraMaxZoomPreference = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int cameraMinZoomPreference = 2130771985;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f01001d
			public const int cardBackgroundColor = 2130771997;
			
			// aapt resource value: 0x7f01001e
			public const int cardCornerRadius = 2130771998;
			
			// aapt resource value: 0x7f01001f
			public const int cardElevation = 2130771999;
			
			// aapt resource value: 0x7f010020
			public const int cardMaxElevation = 2130772000;
			
			// aapt resource value: 0x7f010022
			public const int cardPreventCornerOverlap = 2130772002;
			
			// aapt resource value: 0x7f010021
			public const int cardUseCompatPadding = 2130772001;
			
			// aapt resource value: 0x7f01002c
			public const int centered = 2130772012;
			
			// aapt resource value: 0x7f010019
			public const int circleCrop = 2130771993;
			
			// aapt resource value: 0x7f010034
			public const int clipPadding = 2130772020;
			
			// aapt resource value: 0x7f01001b
			public const int colorScheme = 2130771995;
			
			// aapt resource value: 0x7f010023
			public const int contentPadding = 2130772003;
			
			// aapt resource value: 0x7f010027
			public const int contentPaddingBottom = 2130772007;
			
			// aapt resource value: 0x7f010024
			public const int contentPaddingLeft = 2130772004;
			
			// aapt resource value: 0x7f010025
			public const int contentPaddingRight = 2130772005;
			
			// aapt resource value: 0x7f010026
			public const int contentPaddingTop = 2130772006;
			
			// aapt resource value: 0x7f01002d
			public const int fillColor = 2130772013;
			
			// aapt resource value: 0x7f010035
			public const int footerColor = 2130772021;
			
			// aapt resource value: 0x7f010038
			public const int footerIndicatorHeight = 2130772024;
			
			// aapt resource value: 0x7f010037
			public const int footerIndicatorStyle = 2130772023;
			
			// aapt resource value: 0x7f010039
			public const int footerIndicatorUnderlinePadding = 2130772025;
			
			// aapt resource value: 0x7f010036
			public const int footerLineHeight = 2130772022;
			
			// aapt resource value: 0x7f01003a
			public const int footerPadding = 2130772026;
			
			// aapt resource value: 0x7f010018
			public const int imageAspectRatio = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int imageAspectRatioAdjust = 2130771991;
			
			// aapt resource value: 0x7f010015
			public const int latLngBoundsNorthEastLatitude = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int latLngBoundsNorthEastLongitude = 2130771990;
			
			// aapt resource value: 0x7f010013
			public const int latLngBoundsSouthWestLatitude = 2130771987;
			
			// aapt resource value: 0x7f010014
			public const int latLngBoundsSouthWestLongitude = 2130771988;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f01002f
			public const int orientation = 2130772015;
			
			// aapt resource value: 0x7f01002e
			public const int pageColor = 2130772014;
			
			// aapt resource value: 0x7f010030
			public const int radius = 2130772016;
			
			// aapt resource value: 0x7f01001c
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7f01003c
			public const int selectedBold = 2130772028;
			
			// aapt resource value: 0x7f01003b
			public const int selectedColor = 2130772027;
			
			// aapt resource value: 0x7f010031
			public const int snap = 2130772017;
			
			// aapt resource value: 0x7f010032
			public const int strokeColor = 2130772018;
			
			// aapt resource value: 0x7f010033
			public const int strokeWidth = 2130772019;
			
			// aapt resource value: 0x7f01003d
			public const int textColor = 2130772029;
			
			// aapt resource value: 0x7f01003e
			public const int textSize = 2130772030;
			
			// aapt resource value: 0x7f01003f
			public const int titlePadding = 2130772031;
			
			// aapt resource value: 0x7f010040
			public const int topPadding = 2130772032;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f010028
			public const int vpiCirclePageIndicatorStyle = 2130772008;
			
			// aapt resource value: 0x7f01002a
			public const int vpiTabPageIndicatorStyle = 2130772010;
			
			// aapt resource value: 0x7f01002b
			public const int vpiTabTextStyle = 2130772011;
			
			// aapt resource value: 0x7f010029
			public const int vpiTitlePageIndicatorStyle = 2130772009;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_centered = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_snap = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int default_title_indicator_selected_bold = 2131296258;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f06002f
			public const int DarkYellow = 2131099695;
			
			// aapt resource value: 0x7f06000e
			public const int accent = 2131099662;
			
			// aapt resource value: 0x7f060026
			public const int aqua = 2131099686;
			
			// aapt resource value: 0x7f06002c
			public const int black = 2131099692;
			
			// aapt resource value: 0x7f06002a
			public const int blue = 2131099690;
			
			// aapt resource value: 0x7f060014
			public const int cajeros_menu_lateral = 2131099668;
			
			// aapt resource value: 0x7f060008
			public const int cardview_dark_background = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int cardview_light_background = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int cardview_shadow_end_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int cardview_shadow_start_color = 2131099659;
			
			// aapt resource value: 0x7f06003e
			public const int common_google_signin_btn_text_dark = 2131099710;
			
			// aapt resource value: 0x7f060000
			public const int common_google_signin_btn_text_dark_default = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int common_google_signin_btn_text_dark_disabled = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int common_google_signin_btn_text_dark_focused = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int common_google_signin_btn_text_dark_pressed = 2131099651;
			
			// aapt resource value: 0x7f06003f
			public const int common_google_signin_btn_text_light = 2131099711;
			
			// aapt resource value: 0x7f060004
			public const int common_google_signin_btn_text_light_default = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int common_google_signin_btn_text_light_disabled = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int common_google_signin_btn_text_light_focused = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int common_google_signin_btn_text_light_pressed = 2131099655;
			
			// aapt resource value: 0x7f06002e
			public const int dark_grey = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int dark_greyOrigin = 2131099693;
			
			// aapt resource value: 0x7f060038
			public const int default_circle_indicator_fill_color = 2131099704;
			
			// aapt resource value: 0x7f060039
			public const int default_circle_indicator_page_color = 2131099705;
			
			// aapt resource value: 0x7f06003a
			public const int default_circle_indicator_stroke_color = 2131099706;
			
			// aapt resource value: 0x7f06003b
			public const int default_title_indicator_footer_color = 2131099707;
			
			// aapt resource value: 0x7f06003c
			public const int default_title_indicator_selected_color = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int default_title_indicator_text_color = 2131099709;
			
			// aapt resource value: 0x7f060017
			public const int divider_list_textos = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int fondo_modulos = 2131099670;
			
			// aapt resource value: 0x7f06001e
			public const int fuchsia = 2131099678;
			
			// aapt resource value: 0x7f060029
			public const int green = 2131099689;
			
			// aapt resource value: 0x7f060011
			public const int green_action_bar = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int green_menu_lateral = 2131099666;
			
			// aapt resource value: 0x7f060022
			public const int grey = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int greyOrigin = 2131099681;
			
			// aapt resource value: 0x7f060027
			public const int lime = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int maroon = 2131099685;
			
			// aapt resource value: 0x7f060013
			public const int mercados_menu_lateral = 2131099667;
			
			// aapt resource value: 0x7f06002b
			public const int navy = 2131099691;
			
			// aapt resource value: 0x7f060015
			public const int oficinas_menu_lateral = 2131099669;
			
			// aapt resource value: 0x7f060023
			public const int olive = 2131099683;
			
			// aapt resource value: 0x7f060018
			public const int pink_cajeros = 2131099672;
			
			// aapt resource value: 0x7f06000c
			public const int primary = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int primaryDark = 2131099661;
			
			// aapt resource value: 0x7f060024
			public const int purple = 2131099684;
			
			// aapt resource value: 0x7f060019
			public const int purple_oficinas = 2131099673;
			
			// aapt resource value: 0x7f06001f
			public const int red = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int silver = 2131099680;
			
			// aapt resource value: 0x7f060010
			public const int splash_background = 2131099664;
			
			// aapt resource value: 0x7f060028
			public const int teal = 2131099688;
			
			// aapt resource value: 0x7f06001b
			public const int theme_blue = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int theme_green = 2131099674;
			
			// aapt resource value: 0x7f060030
			public const int vpi__background_holo_dark = 2131099696;
			
			// aapt resource value: 0x7f060031
			public const int vpi__background_holo_light = 2131099697;
			
			// aapt resource value: 0x7f060034
			public const int vpi__bright_foreground_disabled_holo_dark = 2131099700;
			
			// aapt resource value: 0x7f060035
			public const int vpi__bright_foreground_disabled_holo_light = 2131099701;
			
			// aapt resource value: 0x7f060032
			public const int vpi__bright_foreground_holo_dark = 2131099698;
			
			// aapt resource value: 0x7f060033
			public const int vpi__bright_foreground_holo_light = 2131099699;
			
			// aapt resource value: 0x7f060036
			public const int vpi__bright_foreground_inverse_holo_dark = 2131099702;
			
			// aapt resource value: 0x7f060037
			public const int vpi__bright_foreground_inverse_holo_light = 2131099703;
			
			// aapt resource value: 0x7f06001c
			public const int white = 2131099676;
			
			// aapt resource value: 0x7f06000f
			public const int window_background = 2131099663;
			
			// aapt resource value: 0x7f06001d
			public const int yellow = 2131099677;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080000
			public const int cardview_compat_inset_shadow = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_default_elevation = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_default_radius = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int default_circle_indicator_radius = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int default_circle_indicator_stroke_width = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int default_title_indicator_clip_padding = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int default_title_indicator_footer_indicator_height = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int default_title_indicator_footer_indicator_underline_padding = 2131230728;
			
			// aapt resource value: 0x7f080006
			public const int default_title_indicator_footer_line_height = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int default_title_indicator_footer_padding = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int default_title_indicator_text_size = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int default_title_indicator_title_padding = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int default_title_indicator_top_padding = 2131230732;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int agencias = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnFinalizarCajeros = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btnFinalizarOficinas = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btnGuardarCajeros = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btnGuardarOficinas = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btnSiguienteCajeros = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btnSiguienteOficinas = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cableado = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int cajeros = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int CajerosMapaPopupBtn = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int CamaraBtn = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int CerrarPopupIco = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_full_open_on_phone = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_dark_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_icon_dark_focused = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_icon_dark_normal = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_icon_dark_pressed = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_icon_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_icon_light_disabled = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_icon_light_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_icon_light_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_icon_light_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_dark_disabled = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_google_signin_btn_text_dark_focused = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_google_signin_btn_text_dark_normal = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_google_signin_btn_text_dark_pressed = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_google_signin_btn_text_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_google_signin_btn_text_light_disabled = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_google_signin_btn_text_light_focused = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_google_signin_btn_text_light_normal = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_google_signin_btn_text_light_pressed = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Compass = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int estacionamientos = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int fachadas = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int finalizadoMercados = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int finalizadoTextos = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int fondo = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int fondo_Seleccionar = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int FotoIcon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int HorarioIco = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icAgencias = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icCableado = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icCajeros = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icCongresos = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icCuestionario = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icEstacionamientos = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icFachadas = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int icMagicos = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int icMercados = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int Icon = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int iconBar = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int iconCajeros = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int iconOficinas = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int icSenalamientos = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int icWiFi = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int KeyIcon_Gris = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int MailIcon_Gris = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int MercadoIco = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int mercados = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int MercadosEditarEliminarIco = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int MercadosEditarEliminarVacioIco = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int MercadosGuardarBtn = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int MercadosMapaPopupBtn = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int MercadosRegresarBtn = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int MercadosSiguienteBtn = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int oficinas = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int OficinasMapaPopupBtn = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int OpcionesMenuIco = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int OrientacionIcon = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int PinIcon = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int pinSenalamientos = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int RegresarBtn = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int senalamiento = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int SenalamientosIcon = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int SenalamientosOpcionActual = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int SenalamientosSiguienteBtn = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int SenalMapaPopupBtn = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int SenalOrientPopupBtn = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int splash = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int splash_screen = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int TextoIcon = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int wifi = 2130837587;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0033
			public const int ErrorLegendMain = 2131361843;
			
			// aapt resource value: 0x7f0a003b
			public const int ImageMenuLateral = 2131361851;
			
			// aapt resource value: 0x7f0a0041
			public const int ImageMenuSimple = 2131361857;
			
			// aapt resource value: 0x7f0a0049
			public const int ImageMercadosGuardarHorario = 2131361865;
			
			// aapt resource value: 0x7f0a004c
			public const int ImageMercadosMenuHorario = 2131361868;
			
			// aapt resource value: 0x7f0a003c
			public const int LinearListMenuLateral = 2131361852;
			
			// aapt resource value: 0x7f0a003e
			public const int LinearListSimpleViewText1 = 2131361854;
			
			// aapt resource value: 0x7f0a004e
			public const int MercadosFotosSigBtn = 2131361870;
			
			// aapt resource value: 0x7f0a0052
			public const int MercadosGuardarBtn = 2131361874;
			
			// aapt resource value: 0x7f0a004f
			public const int MercadosIndicator = 2131361871;
			
			// aapt resource value: 0x7f0a0047
			public const int MercadosMainSiguienteBtn = 2131361863;
			
			// aapt resource value: 0x7f0a0048
			public const int MercadosMapaPopupBtn = 2131361864;
			
			// aapt resource value: 0x7f0a0054
			public const int MercadosRegresarBtn = 2131361876;
			
			// aapt resource value: 0x7f0a0056
			public const int MercadosSiguienteBtn = 2131361878;
			
			// aapt resource value: 0x7f0a006e
			public const int MercadosTxtRegresarBtn = 2131361902;
			
			// aapt resource value: 0x7f0a0070
			public const int MercadosTxtSiguienteBtn = 2131361904;
			
			// aapt resource value: 0x7f0a00af
			public const int SenalFotosSigBtn = 2131361967;
			
			// aapt resource value: 0x7f0a00ae
			public const int SenalMapaPopupBtn = 2131361966;
			
			// aapt resource value: 0x7f0a00ad
			public const int SenalMapaSigBtn = 2131361965;
			
			// aapt resource value: 0x7f0a00bf
			public const int SenalOrientPopupBtn = 2131361983;
			
			// aapt resource value: 0x7f0a00b3
			public const int SenalOrientSigBtn = 2131361971;
			
			// aapt resource value: 0x7f0a00c3
			public const int SenalTxtFinalizarBtn = 2131361987;
			
			// aapt resource value: 0x7f0a003d
			public const int TextViewMenuLateral = 2131361853;
			
			// aapt resource value: 0x7f0a003f
			public const int TextViewMenuSimple = 2131361855;
			
			// aapt resource value: 0x7f0a004a
			public const int TextViewMercadosGuardarHorario = 2131361866;
			
			// aapt resource value: 0x7f0a0040
			public const int TextViewSubMenuSimple = 2131361856;
			
			// aapt resource value: 0x7f0a004b
			public const int TextViewSubMercadosGuardarHorario = 2131361867;
			
			// aapt resource value: 0x7f0a0005
			public const int adjust_height = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int adjust_width = 2131361798;
			
			// aapt resource value: 0x7f0a000a
			public const int auto = 2131361802;
			
			// aapt resource value: 0x7f0a00a5
			public const int btnCajero = 2131361957;
			
			// aapt resource value: 0x7f0a0020
			public const int btnFinalizarCajeros = 2131361824;
			
			// aapt resource value: 0x7f0a008f
			public const int btnFinalizarOficinas = 2131361935;
			
			// aapt resource value: 0x7f0a00a4
			public const int btnMercado = 2131361956;
			
			// aapt resource value: 0x7f0a00a8
			public const int btnOficina = 2131361960;
			
			// aapt resource value: 0x7f0a00a3
			public const int btnSenalamiento = 2131361955;
			
			// aapt resource value: 0x7f0a001b
			public const int cajerosMapaPopupBtn = 2131361819;
			
			// aapt resource value: 0x7f0a00b2
			public const int compass = 2131361970;
			
			// aapt resource value: 0x7f0a00c5
			public const int containerList = 2131361989;
			
			// aapt resource value: 0x7f0a0076
			public const int containerMercTxtList = 2131361910;
			
			// aapt resource value: 0x7f0a0078
			public const int containerMercTxtSubList = 2131361912;
			
			// aapt resource value: 0x7f0a007a
			public const int containerMercTxtSubList2 = 2131361914;
			
			// aapt resource value: 0x7f0a006a
			public const int containerMercadoHorGuaList = 2131361898;
			
			// aapt resource value: 0x7f0a0066
			public const int containerMercadoHorList = 2131361894;
			
			// aapt resource value: 0x7f0a0068
			public const int containerMercadoHorSubList = 2131361896;
			
			// aapt resource value: 0x7f0a00b1
			public const int containerOrientacionTab = 2131361969;
			
			// aapt resource value: 0x7f0a00c7
			public const int containerSubList = 2131361991;
			
			// aapt resource value: 0x7f0a000b
			public const int dark = 2131361803;
			
			// aapt resource value: 0x7f0a0011
			public const int drawer_layout = 2131361809;
			
			// aapt resource value: 0x7f0a0025
			public const int editTextCajasBanco = 2131361829;
			
			// aapt resource value: 0x7f0a0028
			public const int editTextCajasNoCajeros = 2131361832;
			
			// aapt resource value: 0x7f0a007f
			public const int editTextMercTxtDesc = 2131361919;
			
			// aapt resource value: 0x7f0a0082
			public const int editTextMercTxtNoCom = 2131361922;
			
			// aapt resource value: 0x7f0a0074
			public const int editTextMercTxtNombre = 2131361908;
			
			// aapt resource value: 0x7f0a0099
			public const int editTextOficinaAforo = 2131361945;
			
			// aapt resource value: 0x7f0a009c
			public const int editTextOficinaContacto = 2131361948;
			
			// aapt resource value: 0x7f0a0096
			public const int editTextOficinaNoSalas = 2131361942;
			
			// aapt resource value: 0x7f0a0093
			public const int editTextOficinaNombre = 2131361939;
			
			// aapt resource value: 0x7f0a00cb
			public const int editTextSenalCom = 2131361995;
			
			// aapt resource value: 0x7f0a0014
			public const int footer = 2131361812;
			
			// aapt resource value: 0x7f0a009f
			public const int frameLayout1 = 2131361951;
			
			// aapt resource value: 0x7f0a00bd
			public const int frameLayout11 = 2131361981;
			
			// aapt resource value: 0x7f0a00a2
			public const int frameLayout2 = 2131361954;
			
			// aapt resource value: 0x7f0a00a6
			public const int frameLayout3 = 2131361958;
			
			// aapt resource value: 0x7f0a00b5
			public const int frameLayout5 = 2131361973;
			
			// aapt resource value: 0x7f0a00b7
			public const int frameLayout6 = 2131361975;
			
			// aapt resource value: 0x7f0a00b9
			public const int frameLayout8 = 2131361977;
			
			// aapt resource value: 0x7f0a00bb
			public const int frameLayout9 = 2131361979;
			
			// aapt resource value: 0x7f0a0013
			public const int header_text = 2131361811;
			
			// aapt resource value: 0x7f0a000d
			public const int horizontal = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int hybrid = 2131361792;
			
			// aapt resource value: 0x7f0a0007
			public const int icon_only = 2131361799;
			
			// aapt resource value: 0x7f0a00a7
			public const int imageButton4 = 2131361959;
			
			// aapt resource value: 0x7f0a00a9
			public const int imageButton6 = 2131361961;
			
			// aapt resource value: 0x7f0a00aa
			public const int imageButton7 = 2131361962;
			
			// aapt resource value: 0x7f0a00ab
			public const int imageButton8 = 2131361963;
			
			// aapt resource value: 0x7f0a00ac
			public const int imageButton9 = 2131361964;
			
			// aapt resource value: 0x7f0a002e
			public const int imageView = 2131361838;
			
			// aapt resource value: 0x7f0a00a0
			public const int imageView1 = 2131361952;
			
			// aapt resource value: 0x7f0a002f
			public const int inputCorreo = 2131361839;
			
			// aapt resource value: 0x7f0a009d
			public const int inputCorreoRecuperar = 2131361949;
			
			// aapt resource value: 0x7f0a0030
			public const int inputNIP = 2131361840;
			
			// aapt resource value: 0x7f0a001c
			public const int left_drawer = 2131361820;
			
			// aapt resource value: 0x7f0a000c
			public const int light = 2131361804;
			
			// aapt resource value: 0x7f0a00c0
			public const int linear1 = 2131361984;
			
			// aapt resource value: 0x7f0a0057
			public const int linearApertura = 2131361879;
			
			// aapt resource value: 0x7f0a0051
			public const int linearBtnGuardar = 2131361873;
			
			// aapt resource value: 0x7f0a0053
			public const int linearBtnRegresar = 2131361875;
			
			// aapt resource value: 0x7f0a0055
			public const int linearBtnSiguiente = 2131361877;
			
			// aapt resource value: 0x7f0a006d
			public const int linearBtnTxtRegresar = 2131361901;
			
			// aapt resource value: 0x7f0a006f
			public const int linearBtnTxtSiguiente = 2131361903;
			
			// aapt resource value: 0x7f0a0026
			public const int linearCajaNoCajeros = 2131361830;
			
			// aapt resource value: 0x7f0a0021
			public const int linearCajasTxt2 = 2131361825;
			
			// aapt resource value: 0x7f0a001f
			public const int linearCajasTxtFinalizarBtn = 2131361823;
			
			// aapt resource value: 0x7f0a005a
			public const int linearHorarios = 2131361882;
			
			// aapt resource value: 0x7f0a005d
			public const int linearHorariosEditar = 2131361885;
			
			// aapt resource value: 0x7f0a0060
			public const int linearHorariosPicker1 = 2131361888;
			
			// aapt resource value: 0x7f0a0063
			public const int linearHorariosPicker2 = 2131361891;
			
			// aapt resource value: 0x7f0a0012
			public const int linearLayout1 = 2131361810;
			
			// aapt resource value: 0x7f0a007c
			public const int linearMercTxtDesc = 2131361916;
			
			// aapt resource value: 0x7f0a0075
			public const int linearMercTxtList = 2131361909;
			
			// aapt resource value: 0x7f0a0080
			public const int linearMercTxtNoCom = 2131361920;
			
			// aapt resource value: 0x7f0a0071
			public const int linearMercTxtNombre = 2131361905;
			
			// aapt resource value: 0x7f0a0097
			public const int linearOficinaAforo = 2131361943;
			
			// aapt resource value: 0x7f0a0094
			public const int linearOficinaNoSalas = 2131361940;
			
			// aapt resource value: 0x7f0a0090
			public const int linearOficinasTxt2 = 2131361936;
			
			// aapt resource value: 0x7f0a008e
			public const int linearOficinasTxtFinalizarBtn = 2131361934;
			
			// aapt resource value: 0x7f0a00c4
			public const int linearSenalTxt2 = 2131361988;
			
			// aapt resource value: 0x7f0a00c2
			public const int linearSenalTxtFinalizarBtn = 2131361986;
			
			// aapt resource value: 0x7f0a0022
			public const int linearTextView = 2131361826;
			
			// aapt resource value: 0x7f0a006b
			public const int listViewMercadoHorGuaList = 2131361899;
			
			// aapt resource value: 0x7f0a0067
			public const int listViewMercadoHorList = 2131361895;
			
			// aapt resource value: 0x7f0a0069
			public const int listViewMercadoHorSubList = 2131361897;
			
			// aapt resource value: 0x7f0a0077
			public const int listViewMercadosTxtList = 2131361911;
			
			// aapt resource value: 0x7f0a0079
			public const int listViewMercadosTxtSubList = 2131361913;
			
			// aapt resource value: 0x7f0a007b
			public const int listViewMercadosTxtSubList2 = 2131361915;
			
			// aapt resource value: 0x7f0a00c6
			public const int listViewSenalTxtList = 2131361990;
			
			// aapt resource value: 0x7f0a00c8
			public const int listViewSenalTxtSubList = 2131361992;
			
			// aapt resource value: 0x7f0a0031
			public const int loginButton = 2131361841;
			
			// aapt resource value: 0x7f0a002d
			public const int map = 2131361837;
			
			// aapt resource value: 0x7f0a0039
			public const int map2 = 2131361849;
			
			// aapt resource value: 0x7f0a0019
			public const int mapCajeros = 2131361817;
			
			// aapt resource value: 0x7f0a0046
			public const int mapMarketsWithOverlay = 2131361862;
			
			// aapt resource value: 0x7f0a003a
			public const int mapMenuHome = 2131361850;
			
			// aapt resource value: 0x7f0a0087
			public const int mapOficinas = 2131361927;
			
			// aapt resource value: 0x7f0a00b0
			public const int mapWithOverlay = 2131361968;
			
			// aapt resource value: 0x7f0a0050
			public const int marketopenCameraButton = 2131361872;
			
			// aapt resource value: 0x7f0a004d
			public const int marketpager = 2131361869;
			
			// aapt resource value: 0x7f0a0001
			public const int none = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int normal = 2131361794;
			
			// aapt resource value: 0x7f0a008b
			public const int oficinaFotosSigBtn = 2131361931;
			
			// aapt resource value: 0x7f0a0089
			public const int oficinasMapaPopupBtn = 2131361929;
			
			// aapt resource value: 0x7f0a009e
			public const int recuperarNipButton = 2131361950;
			
			// aapt resource value: 0x7f0a00c1
			public const int regresar_btn = 2131361985;
			
			// aapt resource value: 0x7f0a0003
			public const int satellite = 2131361795;
			
			// aapt resource value: 0x7f0a001d
			public const int scrollView1 = 2131361821;
			
			// aapt resource value: 0x7f0a008c
			public const int signalindicator = 2131361932;
			
			// aapt resource value: 0x7f0a008d
			public const int signalopenCameraButton = 2131361933;
			
			// aapt resource value: 0x7f0a008a
			public const int signalpager = 2131361930;
			
			// aapt resource value: 0x7f0a001a
			public const int siguienteMapaBtn = 2131361818;
			
			// aapt resource value: 0x7f0a0088
			public const int siguienteOficinaBtn = 2131361928;
			
			// aapt resource value: 0x7f0a002c
			public const int space4 = 2131361836;
			
			// aapt resource value: 0x7f0a0083
			public const int space5 = 2131361923;
			
			// aapt resource value: 0x7f0a0029
			public const int spaceNoCajeros = 2131361833;
			
			// aapt resource value: 0x7f0a0008
			public const int standard = 2131361800;
			
			// aapt resource value: 0x7f0a002b
			public const int switchCajasServicio = 2131361835;
			
			// aapt resource value: 0x7f0a0015
			public const int tab1 = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int tab1_cajeros_icon = 2131361814;
			
			// aapt resource value: 0x7f0a0034
			public const int tab1_icon = 2131361844;
			
			// aapt resource value: 0x7f0a0042
			public const int tab1_mercados_icon = 2131361858;
			
			// aapt resource value: 0x7f0a0084
			public const int tab1_oficinas_icon = 2131361924;
			
			// aapt resource value: 0x7f0a001e
			public const int tab2 = 2131361822;
			
			// aapt resource value: 0x7f0a0018
			public const int tab2_cajeros_icon = 2131361816;
			
			// aapt resource value: 0x7f0a0035
			public const int tab2_icon = 2131361845;
			
			// aapt resource value: 0x7f0a0043
			public const int tab2_mercados_icon = 2131361859;
			
			// aapt resource value: 0x7f0a0085
			public const int tab2_oficinas_icon = 2131361925;
			
			// aapt resource value: 0x7f0a0036
			public const int tab3 = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int tab3_icon = 2131361847;
			
			// aapt resource value: 0x7f0a0044
			public const int tab3_mercados_icon = 2131361860;
			
			// aapt resource value: 0x7f0a0086
			public const int tab3_oficinas_icon = 2131361926;
			
			// aapt resource value: 0x7f0a0017
			public const int tab4 = 2131361815;
			
			// aapt resource value: 0x7f0a0038
			public const int tab4_icon = 2131361848;
			
			// aapt resource value: 0x7f0a0045
			public const int tab4_mercados_icon = 2131361861;
			
			// aapt resource value: 0x7f0a0004
			public const int terrain = 2131361796;
			
			// aapt resource value: 0x7f0a0032
			public const int textOlvideNIP = 2131361842;
			
			// aapt resource value: 0x7f0a00a1
			public const int textView1 = 2131361953;
			
			// aapt resource value: 0x7f0a00b8
			public const int textView4 = 2131361976;
			
			// aapt resource value: 0x7f0a00ba
			public const int textView5 = 2131361978;
			
			// aapt resource value: 0x7f0a005c
			public const int textViewAgregar = 2131361884;
			
			// aapt resource value: 0x7f0a0058
			public const int textViewApertura = 2131361880;
			
			// aapt resource value: 0x7f0a0024
			public const int textViewBancosCont = 2131361828;
			
			// aapt resource value: 0x7f0a0023
			public const int textViewCajBancos = 2131361827;
			
			// aapt resource value: 0x7f0a002a
			public const int textViewCajServicio = 2131361834;
			
			// aapt resource value: 0x7f0a0027
			public const int textViewCajaTxtNoCajeros = 2131361831;
			
			// aapt resource value: 0x7f0a0059
			public const int textViewCancelar = 2131361881;
			
			// aapt resource value: 0x7f0a0062
			public const int textViewCierre = 2131361890;
			
			// aapt resource value: 0x7f0a00c9
			public const int textViewComentarios = 2131361993;
			
			// aapt resource value: 0x7f0a005b
			public const int textViewEditar = 2131361883;
			
			// aapt resource value: 0x7f0a005f
			public const int textViewEditarCancelar = 2131361887;
			
			// aapt resource value: 0x7f0a005e
			public const int textViewEditarOk = 2131361886;
			
			// aapt resource value: 0x7f0a0065
			public const int textViewEspacio = 2131361893;
			
			// aapt resource value: 0x7f0a007e
			public const int textViewMercTxtContDesc = 2131361918;
			
			// aapt resource value: 0x7f0a0073
			public const int textViewMercTxtContNombre = 2131361907;
			
			// aapt resource value: 0x7f0a007d
			public const int textViewMercTxtDesc = 2131361917;
			
			// aapt resource value: 0x7f0a0081
			public const int textViewMercTxtNoCom = 2131361921;
			
			// aapt resource value: 0x7f0a0072
			public const int textViewMercTxtNombre = 2131361906;
			
			// aapt resource value: 0x7f0a009a
			public const int textViewOficinaContacto = 2131361946;
			
			// aapt resource value: 0x7f0a009b
			public const int textViewOficinaContactoCont = 2131361947;
			
			// aapt resource value: 0x7f0a0091
			public const int textViewOficinaNombre = 2131361937;
			
			// aapt resource value: 0x7f0a0092
			public const int textViewOficinaNombreCont = 2131361938;
			
			// aapt resource value: 0x7f0a0098
			public const int textViewOficinaTxtAforo = 2131361944;
			
			// aapt resource value: 0x7f0a0095
			public const int textViewOficinaTxtNoSalas = 2131361941;
			
			// aapt resource value: 0x7f0a006c
			public const int textViewSinHorarios = 2131361900;
			
			// aapt resource value: 0x7f0a00ca
			public const int textViewcomentariosCont = 2131361994;
			
			// aapt resource value: 0x7f0a0061
			public const int timePickerApertura = 2131361889;
			
			// aapt resource value: 0x7f0a0064
			public const int timePickerCierre = 2131361892;
			
			// aapt resource value: 0x7f0a000f
			public const int triangle = 2131361807;
			
			// aapt resource value: 0x7f0a00b4
			public const int txtBrujulaGrados = 2131361972;
			
			// aapt resource value: 0x7f0a00b6
			public const int txtBrujulaOrientacion = 2131361974;
			
			// aapt resource value: 0x7f0a00bc
			public const int txtLatGrados = 2131361980;
			
			// aapt resource value: 0x7f0a00be
			public const int txtLongGrados = 2131361982;
			
			// aapt resource value: 0x7f0a0010
			public const int underline = 2131361808;
			
			// aapt resource value: 0x7f0a000e
			public const int vertical = 2131361806;
			
			// aapt resource value: 0x7f0a0009
			public const int wide = 2131361801;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f040001
			public const int default_circle_indicator_orientation = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int default_title_indicator_footer_indicator_style = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int google_play_services_version = 2130968576;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Cajeros = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CajerosTextos = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int geolocalizacion_fragment = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ImageView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Map = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int MenuHome = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int MenuLateral = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int MenuSimple = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Mercados = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MercadosEditarHorario = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MercadosFotos = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int MercadosHorarios = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int MercadosTextos = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Oficinas = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int OficinasFotos = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int OficinasTextos = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int RecuperarNip = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int SeleccionarModulo = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Senalamientos = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int SenalamientosFotos = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int SenalamientosMap = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int SenalamientosOrientacion = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int SenalamientosTextos = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int simple_fragment = 2130903064;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050012
			public const int ApplicationName = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int Hello = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int close_drawer = 2131034139;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_enable_button = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_enable_text = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_enable_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_install_text = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_install_title = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_notification_ticker = 2131034119;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_unknown_issue = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_unsupported_text = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_button = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_update_text = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_update_title = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_wear_update_text = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int common_open_on_phone = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int common_signin_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int common_signin_button_text_long = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int fotos_tab_label = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int geo_tab_label = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int header_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int openCamera = 2131034136;
			
			// aapt resource value: 0x7f05001a
			public const int open_drawer = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int orient_tab_label = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int tab_label = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int textos_tab_label = 2131034135;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f07000c
			public const int CustomCirclePageIndicator = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int CustomTabPageIndicator = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int CustomTabPageIndicator_Text = 2131165198;
			
			// aapt resource value: 0x7f07000b
			public const int CustomTitlePageIndicator = 2131165195;
			
			// aapt resource value: 0x7f070005
			public const int MyTheme = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int MyTheme_Base = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int MyTheme_ListFont = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int MyTheme_MenuLateral = 2131165193;
			
			// aapt resource value: 0x7f070007
			public const int MyTheme_Senalamientos = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int MyTheme_Splash = 2131165190;
			
			// aapt resource value: 0x7f07000a
			public const int StyledIndicators = 2131165194;
			
			// aapt resource value: 0x7f070015
			public const int TextAppearance_TabPageIndicator = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int Theme_PageIndicatorDefaults = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int Widget = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Widget_CirclePageIndicator = 2131165201;
			
			// aapt resource value: 0x7f070013
			public const int Widget_TabPageIndicator = 2131165203;
			
			// aapt resource value: 0x7f070014
			public const int Widget_TabPageIndicator_Text = 2131165204;
			
			// aapt resource value: 0x7f070012
			public const int Widget_TitlePageIndicator = 2131165202;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] CirclePageIndicator = new int[] {
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] LoadingImageView = new int[] {
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 18
			public const int MapAttrs_cameraMaxZoomPreference = 18;
			
			// aapt resource value: 17
			public const int MapAttrs_cameraMinZoomPreference = 17;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 21
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 22;
			
			// aapt resource value: 19
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 20;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] SignInButton = new int[] {
					2130771994,
					2130771995,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] TitlePageIndicator = new int[] {
					2130772020,
					2130772021,
					2130772022,
					2130772023,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031,
					2130772032};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130772008,
					2130772009,
					2130772010,
					2130772011};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiTabTextStyle = 3;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
